/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseBreadcrumb: typeof import('./src/components/shared/BaseBreadcrumb.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiChildCard: typeof import('./src/components/shared/UiChildCard.vue')['default']
    UiParentCard: typeof import('./src/components/shared/UiParentCard.vue')['default']
  }
}
